// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api_forum.Migrations.Forum
{
    [DbContext(typeof(ForumContext))]
    [Migration("20230914185233_ForumInit")]
    partial class ForumInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "USER",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Entities.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cabinet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LatestLoginOnForum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            BirthDate = "0",
                            Cabinet = "0",
                            Company = "My company",
                            ConcurrencyStamp = "7385ca32-aff9-4f49-ad16-7f64b4fa2754",
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 352, DateTimeKind.Local).AddTicks(6433),
                            Division = "My division",
                            Email = "Admin@admin.by",
                            EmailConfirmed = false,
                            FirstName = "System",
                            InternalPhone = "0",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.BY",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEJmQy9UwxkODjbb/iQlo7ezznBC5omr0sEhFEoTgafpAxZZRFsyVCFG8NXKSc2SGJA==",
                            PhoneNumber = "0",
                            PhoneNumberConfirmed = false,
                            Position = "Administrator",
                            SecurityStamp = "FGXU4FIM2LMJZFDJD3YCUQEHQRZY4GSS",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Entities.Models.File.ForumFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ForumPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ForumUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id")
                        .HasName("PK_ForumFile");

                    b.HasIndex("ForumPostId");

                    b.HasIndex("ForumUserId");

                    b.ToTable("ForumFile", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumAccount", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id")
                        .HasName("PK_ForumAccount");

                    b.HasIndex("AccountTypeId")
                        .IsUnique()
                        .HasFilter("[AccountTypeId] IS NOT NULL");

                    b.ToTable("ForumAccount", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumAccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id")
                        .HasName("PK_ForumAccountType");

                    b.ToTable("ForumAccountType", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<int?>("ForumCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForumSubTitle")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ForumTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR");

                    b.Property<int?>("ForumUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalTopics")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalViews")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id")
                        .HasName("PK_ForumBase");

                    b.HasIndex("ForumCategoryId");

                    b.HasIndex("ForumUserId");

                    b.ToTable("ForumBase", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(6152),
                            ForumCategoryId = 1,
                            ForumSubTitle = "Test forum subtitle 1",
                            ForumTitle = "Test forum title 1",
                            ForumUserId = 1,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(6155),
                            ForumCategoryId = 2,
                            ForumSubTitle = "Test forum subtitle 2",
                            ForumTitle = "Test forum title 2",
                            ForumUserId = 1,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(6157),
                            ForumCategoryId = 2,
                            ForumSubTitle = "Test forum subtitle 3",
                            ForumTitle = "Test forum title 3",
                            ForumUserId = 1,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(6159),
                            ForumCategoryId = 2,
                            ForumSubTitle = "Test forum subtitle 4",
                            ForumTitle = "Test forum title 4",
                            ForumUserId = 1,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(6161),
                            ForumCategoryId = 2,
                            ForumSubTitle = "Test forum subtitle 5",
                            ForumTitle = "Test forum title 5",
                            ForumUserId = 1,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(6162),
                            ForumCategoryId = 2,
                            ForumSubTitle = "Test forum subtitle 6",
                            ForumTitle = "Test forum title 6",
                            ForumUserId = 1,
                            TotalViews = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<int?>("ForumUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("TotalForums")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTopics")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id")
                        .HasName("PK_ForumCategory");

                    b.HasIndex("ForumUserId");

                    b.ToTable("ForumCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(1550),
                            ForumUserId = 1,
                            Name = "Test category 1",
                            TotalForums = 1,
                            TotalTopics = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(1553),
                            ForumUserId = 1,
                            Name = "Test category 2",
                            TotalForums = 5,
                            TotalTopics = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(1555),
                            ForumUserId = 1,
                            Name = "Test category 3",
                            TotalForums = 0,
                            TotalTopics = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(1556),
                            ForumUserId = 1,
                            Name = "Test category 4",
                            TotalForums = 0,
                            TotalTopics = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(1558),
                            ForumUserId = 1,
                            Name = "Test category 5",
                            TotalForums = 0,
                            TotalTopics = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 354, DateTimeKind.Local).AddTicks(1560),
                            ForumUserId = 1,
                            Name = "Test category 6",
                            TotalForums = 0,
                            TotalTopics = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<int>("ForumFileId")
                        .HasColumnType("int");

                    b.Property<int?>("ForumTopicId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ForumUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostText")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id")
                        .HasName("PK_ForumPost");

                    b.HasIndex("ForumTopicId");

                    b.HasIndex("ForumUserId");

                    b.ToTable("ForumPost", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(3990),
                            ForumFileId = 0,
                            ForumTopicId = 1,
                            ForumUserId = 1,
                            Likes = 0,
                            PostText = "1111111111111111111111"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(3996),
                            ForumFileId = 0,
                            ForumTopicId = 2,
                            ForumUserId = 1,
                            Likes = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(3997),
                            ForumFileId = 0,
                            ForumTopicId = 2,
                            ForumUserId = 1,
                            Likes = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(3998),
                            ForumFileId = 0,
                            ForumTopicId = 2,
                            ForumUserId = 1,
                            Likes = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(4000),
                            ForumFileId = 0,
                            ForumTopicId = 2,
                            ForumUserId = 1,
                            Likes = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(4001),
                            ForumFileId = 0,
                            ForumTopicId = 1,
                            ForumUserId = 1,
                            Likes = 0,
                            PostText = "222222222222222222"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(4002),
                            ForumFileId = 0,
                            ForumTopicId = 1,
                            ForumUserId = 1,
                            Likes = 0,
                            PostText = "333333333333333"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(4004),
                            ForumFileId = 0,
                            ForumTopicId = 1,
                            ForumUserId = 1,
                            Likes = 0,
                            PostText = "44444444444444"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(4005),
                            ForumFileId = 0,
                            ForumTopicId = 1,
                            ForumUserId = 1,
                            Likes = 0,
                            PostText = "555555555555555"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(4006),
                            ForumFileId = 0,
                            ForumTopicId = 1,
                            ForumUserId = 1,
                            Likes = 0,
                            PostText = "666666666666666"
                        });
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<int?>("ForumBaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ForumUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("TotalPosts")
                        .HasColumnType("int");

                    b.Property<int>("TotalViews")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id")
                        .HasName("PK_ForumTopic");

                    b.HasIndex("ForumBaseId");

                    b.HasIndex("ForumUserId");

                    b.ToTable("ForumTopic", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(734),
                            ForumBaseId = 1,
                            ForumUserId = 1,
                            Name = "Test forum topic 1",
                            TotalPosts = 0,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(742),
                            ForumBaseId = 2,
                            ForumUserId = 1,
                            Name = "Test forum topic 2",
                            TotalPosts = 0,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(743),
                            ForumBaseId = 2,
                            ForumUserId = 1,
                            Name = "Test forum topic 3",
                            TotalPosts = 0,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(745),
                            ForumBaseId = 2,
                            ForumUserId = 1,
                            Name = "Test forum topic 4",
                            TotalPosts = 0,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(746),
                            ForumBaseId = 2,
                            ForumUserId = 1,
                            Name = "Test forum topic 5",
                            TotalPosts = 0,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(747),
                            ForumBaseId = 1,
                            ForumUserId = 1,
                            Name = "Test forum topic 1a",
                            TotalPosts = 0,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(749),
                            ForumBaseId = 1,
                            ForumUserId = 1,
                            Name = "Test forum topic 1b",
                            TotalPosts = 0,
                            TotalViews = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 9, 14, 21, 52, 33, 355, DateTimeKind.Local).AddTicks(750),
                            ForumBaseId = 1,
                            ForumUserId = 1,
                            Name = "Test forum topic 1c",
                            TotalPosts = 0,
                            TotalViews = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumTopicCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ForumTopicId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PostCounter")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_ForumTopicCounter");

                    b.HasIndex("ForumTopicId")
                        .IsUnique()
                        .HasFilter("[ForumTopicId] IS NOT NULL");

                    b.ToTable("ForumTopicCounter", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ForumTopicId = 1,
                            PostCounter = 6
                        },
                        new
                        {
                            Id = 2,
                            ForumTopicId = 2,
                            PostCounter = 4
                        },
                        new
                        {
                            Id = 3,
                            ForumTopicId = 3,
                            PostCounter = 0
                        },
                        new
                        {
                            Id = 4,
                            ForumTopicId = 4,
                            PostCounter = 0
                        },
                        new
                        {
                            Id = 5,
                            ForumTopicId = 5,
                            PostCounter = 0
                        },
                        new
                        {
                            Id = 6,
                            ForumTopicId = 6,
                            PostCounter = 0
                        },
                        new
                        {
                            Id = 7,
                            ForumTopicId = 7,
                            PostCounter = 0
                        },
                        new
                        {
                            Id = 8,
                            ForumTopicId = 8,
                            PostCounter = 0
                        });
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarImgSrc")
                        .HasColumnType("NVARCHAR");

                    b.Property<int?>("Karma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("TotalPostCounter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id")
                        .HasName("PK_ForumUser");

                    b.HasIndex("TotalPostCounter");

                    b.ToTable("ForumUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 1,
                            TotalPostCounter = 10
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Models.File.ForumFile", b =>
                {
                    b.HasOne("Entities.Models.Forum.ForumPost", "ForumPost")
                        .WithMany("ForumFiles")
                        .HasForeignKey("ForumPostId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ForumPost_ForumFile_Id");

                    b.HasOne("Entities.Models.Forum.ForumUser", "ForumUser")
                        .WithMany("ForumFiles")
                        .HasForeignKey("ForumUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ForumUser_ForumFile_ForumUserId");

                    b.Navigation("ForumPost");

                    b.Navigation("ForumUser");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumAccount", b =>
                {
                    b.HasOne("Entities.Models.Forum.ForumAccountType", "ForumAccountType")
                        .WithOne("ForumAccount")
                        .HasForeignKey("Entities.Models.Forum.ForumAccount", "AccountTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ForumAccount_ForumAccountType_Id");

                    b.HasOne("Entities.Models.Forum.ForumUser", "ForumUser")
                        .WithOne("ForumAccount")
                        .HasForeignKey("Entities.Models.Forum.ForumAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ForumAccount_ForumUser_Id");

                    b.Navigation("ForumAccountType");

                    b.Navigation("ForumUser");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumBase", b =>
                {
                    b.HasOne("Entities.Models.Forum.ForumCategory", "ForumCategory")
                        .WithMany("ForumBases")
                        .HasForeignKey("ForumCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ForumCategory_ForumBase_Id");

                    b.HasOne("Entities.Models.Forum.ForumUser", "ForumUser")
                        .WithMany()
                        .HasForeignKey("ForumUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ForumBase_ForumUser_Id");

                    b.Navigation("ForumCategory");

                    b.Navigation("ForumUser");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumCategory", b =>
                {
                    b.HasOne("Entities.Models.Forum.ForumUser", "ForumUser")
                        .WithMany()
                        .HasForeignKey("ForumUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ForumCategory_ForumUser_Id");

                    b.Navigation("ForumUser");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumPost", b =>
                {
                    b.HasOne("Entities.Models.Forum.ForumTopic", "ForumTopic")
                        .WithMany("ForumPosts")
                        .HasForeignKey("ForumTopicId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ForumTopic_ForumPost_ForumTopicId");

                    b.HasOne("Entities.Models.Forum.ForumUser", "ForumUser")
                        .WithMany()
                        .HasForeignKey("ForumUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ForumPost_ForumUser_Id");

                    b.Navigation("ForumTopic");

                    b.Navigation("ForumUser");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumTopic", b =>
                {
                    b.HasOne("Entities.Models.Forum.ForumBase", "ForumBase")
                        .WithMany("ForumTopics")
                        .HasForeignKey("ForumBaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ForumBase_ForumTopic_ForumBaseId");

                    b.HasOne("Entities.Models.Forum.ForumUser", "ForumUser")
                        .WithMany()
                        .HasForeignKey("ForumUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ForumTopic_ForumUser_Id");

                    b.Navigation("ForumBase");

                    b.Navigation("ForumUser");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumTopicCounter", b =>
                {
                    b.HasOne("Entities.Models.Forum.ForumTopic", "ForumTopic")
                        .WithOne("ForumTopicCounter")
                        .HasForeignKey("Entities.Models.Forum.ForumTopicCounter", "ForumTopicId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_ForumTopic_ForumTopicCounter_Id");

                    b.Navigation("ForumTopic");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumUser", b =>
                {
                    b.HasOne("Entities.Models.AppUser", "AppUser")
                        .WithOne("ForumUser")
                        .HasForeignKey("Entities.Models.Forum.ForumUser", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ForumUser_AppUser_Id");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Entities.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Entities.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Entities.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Entities.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Entities.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.AppUser", b =>
                {
                    b.Navigation("ForumUser")
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumAccountType", b =>
                {
                    b.Navigation("ForumAccount");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumBase", b =>
                {
                    b.Navigation("ForumTopics");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumCategory", b =>
                {
                    b.Navigation("ForumBases");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumPost", b =>
                {
                    b.Navigation("ForumFiles");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumTopic", b =>
                {
                    b.Navigation("ForumPosts");

                    b.Navigation("ForumTopicCounter");
                });

            modelBuilder.Entity("Entities.Models.Forum.ForumUser", b =>
                {
                    b.Navigation("ForumAccount")
                        .IsRequired();

                    b.Navigation("ForumFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
