services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: es
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      #ELASTIC_PASSWORD: $INITIAL_PASSWORD
      xpack.security.enabled: "false"
    volumes:
      - ./configs/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      #- "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elkf-sd-ms-arc
  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.1
    container_name: log
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./configs/logstash/pipeline/logstash-sd-ms-arc.config:/usr/share/logstash/pipeline/logstash-sd-ms-arc.config
      #- ./logstash/nginx.log:/home/nginx.log
    ports:
      #- "5000:5000/tcp"
      #- "5000:5000/udp"
      - "5044:5044"
      #- "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elkf-sd-ms-arc
    command: logstash -f /usr/share/logstash/pipeline/logstash-sd-ms-arc.config
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    container_name: kib
    environment:
      #ELASTICSEARCH_USERNAME: "kibana"
      #ELASTICSEARCH_PASSWORD: ""
      #ELASTICSEARCH_USERNAME: "elastic"
      #ELASTICSEARCH_PASSWORD: "yVfK663iWNuIQGdwDSp7"
      server.ssl.enabled: "false"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elkf-sd-ms-arc
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.9.1
    container_name: fb
    # Need to override user so we can access the log files, and docker.sock
    user: root
    networks:
      - elkf-sd-ms-arc
    mem_limit: 1g
    volumes:
      - ./configs/filebeat/filebeat.yml:/usr/share/filebeat.yml
      - ./logs:/var/log/sd-ms-arc-log
    #configs:
    #  - source: fb_config
    #    target: /usr/share/filebeat/filebeat.yml
    # disable strict permission checks
    command: ["--strict.perms=false"]
networks:
  elkf-sd-ms-arc:
    driver: bridge