version: "3.7"

networks:
  elk-sd-ms-arc:
    
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    networks:
      - elk-sd-ms-arc
    environment:
      - discovery.type=single-node
    mem_limit: 4g
      
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elk-sd-ms-arc
    depends_on:
      - elasticsearch
    mem_limit: 1g
    
  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.1
    build:
       context: logstash/
    container_name: logstash
    networks:
      - elk-sd-ms-arc
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    restart: always
    mem_limit: 2g
    environment:
      - "LS_JAVA_OPTS=-Xmx1g -Xms1g"